# Generated by Django 4.1.2 on 2022-11-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='construido_por',
            field=models.CharField(default='', max_length=38),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='nombre_blog',
            field=models.CharField(max_length=28),
        ),
    ]
